<?php echo $this->doctype(); ?>
<html>
    <head>
        <title>ZF2 Skeleton by AFYM</title>
        <style type="text/css">
			.error {color: red;}
		</style>
    </head>
    <body>
        <div id="logo">
        	<a href="<?php echo $this->actionLink('') ?>">
        		<img src="http://icons.iconarchive.com/icons/simiographics/mixed/512/Book-icon.png" width="100" height="100"/>
        	</a>
        </div>
        <h1 style="color: yellowgreen; text-align: center;"> Zend Framework <span style="color: black;">2</span> <span style="color: blue;">Book Store</span></h1>
        <div style="background-color: oldlace; border : 1px solid black; padding: 20px;">
            <?php echo $this->content ?>
        </div>
    </body>
</html>